spring:
  application:
    name: petaverse-backend
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/petaverse
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
  
  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-here-make-it-long-and-secure}
  expiration: 86400000 # 24 hours

# File Storage Configuration
file:
  upload:
    path: ./uploads/
    allowed-types: jpg,jpeg,png,gif,mp4,avi,mov

# Logging Configuration
logging:
  level:
    com.petaverse: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Custom Application Properties
app:
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://localhost:8081
  notification:
    enabled: true
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY:your-google-maps-api-key} 