package com.petaverse.entity;

public enum NotificationType {
    ADOPTION_REQUEST,
    ADOPTION_APPROVED,
    ADOPTION_REJECTED,
    NEW_MESSAGE,
    LOST_PET_FOUND,
    LOST_PET_REPORT,
    VET_APPOINTMENT,
    VACCINATION_REMINDER,
    SYSTEM_ANNOUNCEMENT,
    PET_BIRTHDAY,
    ADOPTION_SUCCESS,
    WELCOME,
    PASSWORD_RESET,
    EMAIL_VERIFICATION,
    ACCOUNT_SUSPENDED,
    PAYMENT_RECEIVED,
    PAYMENT_FAILED,
    REVIEW_REQUEST,
    FOLLOW_UP,
    EMERGENCY_ALERT
}
